Repository fga-eps-mds/2022-1-Visualeasy-Controle, pull requests merged in 2022-08, with the labels that each got.

#25 06 buscar variaveis
  __tests__/VariavelRequest.test.js
  csvFiles/dados_unb.csv
  package-lock.json
  package.json
  postgresScripts/variavel-schema.sql
  src/controller/VariavelController.js
  src/controller/VariavelRequest.js
  src/routes/variavel.routes.js
  src/server.js
Labels: Back-end, Release 01

#26 Merge Devel to Main R1
  Dockerfile
  README.md
  __tests__/App.test.js
  __tests__/ModelVariavel.test.js
  __tests__/VariavelController.test.js
  __tests__/VariavelRequest.test.js
  __tests__/sum.test.js
  csvFiles/dados_unb.csv
  docker-compose.yml
  heroku.yml
  package-lock.json
  package.json
  postgresScripts/variavel-schema.sql
  sonar-project.properties
  src/app.js
  src/config/db.js
  src/controller/FindHelloWolrdResolve.js
  src/controller/HelloWorldController.js
  src/controller/VariavelController.js
  src/controller/VariavelCreate.js
  src/controller/VariavelRequest.js
  src/models/sum.js
  src/models/variavel.js
  src/routes/helloworld.routes.js
  src/routes/index.js
  src/routes/variavel.routes.js
  src/server.js
Labels: DEVOPS, ANALYTICS, EPS, Back-end, Release 01

#29 27 fix bug https
  .editorconfig
  .github/workflows/build.yml
  .gitignore
  cert.pem
  csr.pem
  key.pem
  package-lock.json
  package.json
  src/config/db.js
  src/server.js
Labels: HOTFIX, DEVOPS, ANALYTICS, EPS, Back-end

#30 03 initiate axios
  __tests__/App.test.js
  __tests__/VariavelController.test.js
  __tests__/VariavelRequest.test.js
  docker-compose.yml
  package-lock.json
  package.json
  postgresScripts/variavel-schema.sql
  src/app.js
  src/controller/VariavelController.js
  src/controller/VariavelCreate.js
  src/controller/VariavelRequest.js
  src/routes/index.js
  src/routes/variavel.routes.js
Labels: DEVOPS, Back-end

#31 05 intervalo pre definido
  __tests__/VariavelRequest.test.js
  src/controller/VariavelController.js
  src/controller/VariavelRequest.js
  src/routes/variavel.routes.js
Labels: FEATURE, EPS, Back-end

#32 Devops heroku fix
  .github/workflows/build.yml
  .github/workflows/release.yml
  __tests__/ModelVariavel.test.js
  __tests__/VariavelController.test.js
  __tests__/VariavelControllerExceptions.test.js
  __tests__/VariavelRequest.test.js
  src/app.js
  src/config/db.js
  src/controller/VariavelController.js
  src/controller/VariavelCreate.js
  src/models/variavel.js
Labels: FEATURE, DEVOPS, HARD, Back-end

#33 Merge Devel to Main R2
  .github/workflows/build.yml
  .github/workflows/release.yml
  __tests__/App.test.js
  __tests__/ModelVariavel.test.js
  __tests__/VariavelController.test.js
  __tests__/VariavelControllerExceptions.test.js
  __tests__/VariavelRequest.test.js
  docker-compose.yml
  package-lock.json
  package.json
  postgresScripts/variavel-schema.sql
  src/app.js
  src/config/db.js
  src/controller/VariavelController.js
  src/controller/VariavelCreate.js
  src/controller/VariavelRequest.js
  src/models/variavel.js
  src/routes/index.js
  src/routes/variavel.routes.js
Labels: DEVOPS, ANALYTICS, EPS, Back-end, Release 2

#34 Us08 mult variaveis
  .github/workflows/release.yml
  .gitignore
  __tests__/VariavelControllerExceptions.test.js
  __tests__/VariavelRequest.test.js
  csvFiles/.gitkeep
  csvFiles/dados_unb.csv
  package-lock.json
  package.json
  postgresScripts/variavel-schema.sql
  src/app.js
  src/controller/VariavelRequest.js
  src/util/sqlQuery.js
Labels: FEATURE, US, HARD, Back-end

#35 Diminuindo duplicação sqlQuery
  src/util/sqlQuery.js
Labels: HOTFIX, EPS, Back-end

#36 Devops deploy04
  src/app.js
Labels: HOTFIX, DEVOPS, EPS, Back-end

#38 Hotfix R3
  src/app.js
  src/controller/VariavelCreate.js
Labels: HOTFIX, DEVOPS, ANALYTICS, Release 3
